# Generated by Django 3.0.8 on 2020-07-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audit',
            fields=[
                ('student_roll_number', models.AutoField(primary_key=True, serialize=False)),
                ('verifying_faculty', models.CharField(max_length=30)),
                ('updated_dt', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 14, 8, 49, 916965), null=True)),
            ],
            options={
                'db_table': 'audit',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_roll_number', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('mode_of_admission', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('current_address', models.CharField(max_length=30)),
                ('permanent_address', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('father_mobile_number', models.CharField(max_length=30)),
                ('created_dt', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 14, 8, 49, 916965), null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
