# Generated by Django 3.0.8 on 2020-07-14 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20200714_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='updated_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 19, 1, 22, 132005), null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 19, 1, 22, 132005), null=True),
        ),
    ]
