# Generated by Django 3.0.8 on 2020-07-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'test_model',
            },
        ),
    ]
