# Generated by Django 3.0.8 on 2020-07-17 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test_model',
            old_name='id_s',
            new_name='s_id',
        ),
    ]
