# Generated by Django 3.0.8 on 2020-07-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_app', '0002_auto_20200717_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'test_detail',
            },
        ),
    ]
