# Generated by Django 3.0.6 on 2020-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='constituents',
            fields=[
                ('constituent_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituent_name', models.CharField(max_length=80)),
                ('district_id', models.IntegerField()),
            ],
            options={
                'db_table': 'constituents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='parties',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_symbol', models.CharField(max_length=80)),
                ('party_started', models.DateField()),
                ('started_leader', models.CharField(max_length=60)),
                ('current_leader', models.CharField(max_length=70)),
                ('party_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'parties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='party_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=70)),
                ('member_age', models.IntegerField()),
                ('constituent_id', models.IntegerField()),
                ('party_id', models.IntegerField()),
                ('ruling_start_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'party_member',
                'managed': False,
            },
        ),
    ]
